dist: trusty
sudo: required
language: node_js
cache:
  directories:
  - node_modules
node_js:
- 6
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5
script: npm run test-ci
deploy:
  provider: heroku
  api_key:
    secure: maVGC4MG3370c5iIrzkokZ74JLPcg0sk7Vy4hlzevltgMXQO0pmphyLcz9X53+bE5S0b51qnnksNXj2+F7Y3mQpnVmApDDpmMJ243mNGArpRTuWG6eEuTF3mzPZrS8aEWg/uUxg0XYKpXeKDqBEZYP2drYhbh1CyGD2/+QPvye9vkCBp6LmXc4byDjdakUz+SprviCJO9ine/GZ45zF5cNpRuKSfYjwG4lcjuRjdNy5TnOuK5wU4nYm35RhccBRVS5QhakH5Vt7v4W/8evmCvCsQ/+Go+dXViuLzgtwVDH+r/lnzlANAHrtzwyUr4T8iYgICZxfXaC1eOahoX3EG8mXd5cmX2pw75GxdqHys5gHi97xICAIshCHnXc+mjNng9Ik6tS7YEnIbTSm0bNjWQLoY6sq3LT+kOLcHOjmGpjiKLFzMxgXnaDZJmjY6+ZvvINT2tUdhlZ++4+1YVOz6PhZ89ehAJarBvhdnVLcP1btQxtC65ExKJ5nFoS50Pxj/V3Ta22IY04c5LvhSoK+2Qat5kz7mBsEQlZIkmfAMCVEYXeVcCmA/CFO4zWjQsKQw1mbPvfCnEkKf8tdYiPepeFW4XmKd2XFbJtpGY/cHV6r3osl/15i9w7biRC250nbi4qm7jqpcGjWh9CzMbjJaW3wnY+wYpEp94QN9y4W9g2E=
  app: pim-suite
  on:
    repo: sys-devel-d/pimp-frontend
